// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_books/test/features/favourites/repository/favorites_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_books/features/favorites/datasources/favorites_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IFavoriteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFavoriteDatasource extends _i1.Mock
    implements _i2.IFavoriteDatasource {
  MockIFavoriteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> fetchFavorites() =>
      (super.noSuchMethod(Invocation.method(#fetchFavorites, []),
              returnValue: Future<List<String>>.value(<String>[]))
          as _i3.Future<List<String>>);
  @override
  _i3.Future<void> addToFavorites(String? id) =>
      (super.noSuchMethod(Invocation.method(#addToFavorites, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> removeFromFavorites(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeFromFavorites, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
